#import <Foundation/Foundation.h>

#define BTDropInLocalizedString(KEY) [BTDropInLocalizedString KEY]

@interface BTDropInLocalizedString : NSObject

+ (NSString *)DROP_IN_CHANGE_PAYMENT_METHOD_BUTTON_TEXT;
+ (NSString *)ERROR_ALERT_OK_BUTTON_TEXT;
+ (NSString *)ERROR_ALERT_CANCEL_BUTTON_TEXT;
+ (NSString *)ERROR_ALERT_TRY_AGAIN_BUTTON_TEXT;
+ (NSString *)ERROR_ALERT_CONNECTION_ERROR;
+ (NSString *)DEFAULT_CALL_TO_ACTION;
+ (NSString *)CARD_FORM_SECTION_HEADER;
+ (NSString *)SELECT_PAYMENT_METHOD_TITLE;
+ (NSString *)ERROR_SAVING_CARD_ALERT_TITLE;
+ (NSString *)ERROR_SAVING_CARD_MESSAGE;
+ (NSString *)ERROR_SAVING_PAYMENT_METHOD_ALERT_TITLE;
+ (NSString *)ERROR_SAVING_PAYPAL_ACCOUNT_ALERT_MESSAGE;
+ (NSString *)ADD_PAYMENT_METHOD_VIEW_CONTROLLER_TITLE;

@end
